### ISSUE TITLE
Delete functunality required in Prompts

### ISSUE THREAD

**Issue by MisbahNoorAwan** [MisbahNoorAwan/Promptopia#1]
![issue](https://github.com/MisbahNoorAwan/Promptopia/assets/77966399/bdd8918e-46b9-4bd4-817c-a5c7aada99c5)

We have a function called handleDelete() in prompt creation,.
Requirement: When the delete button on prompt cart is clicked, the Cart should be deleted, both from the database and the front-end

**Comment by ALIRAZA17** [comment]
@MisbahNoorAwan Can i work on this issue?
